"""empty message

Revision ID: 3234909e72b9
Revises: 7231bc02a6e8
Create Date: 2018-09-03 11:55:01.059526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3234909e72b9'
down_revision = '7231bc02a6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.String(length=18), nullable=True))
    op.drop_index('phone_number', table_name='user')
    op.create_unique_constraint(None, 'user', ['mobile'])
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', mysql.VARCHAR(length=18), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('phone_number', 'user', ['phone_number'], unique=True)
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###
