"""empty message

Revision ID: 7231bc02a6e8
Revises: 987cf31d0a3b
Create Date: 2018-09-03 08:26:58.433182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7231bc02a6e8'
down_revision = '987cf31d0a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift',
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('book_title', sa.String(length=50), nullable=True),
    sa.Column('book_author', sa.String(length=30), nullable=True),
    sa.Column('book_img', sa.String(length=50), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requester_nickname', sa.String(length=20), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('gift_id', sa.Integer(), nullable=True),
    sa.Column('contributor_nickname', sa.String(length=20), nullable=True),
    sa.Column('pending', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('contrib_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'donate_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('donate_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'contrib_count')
    op.drop_table('drift')
    # ### end Alembic commands ###
