"""empty message

Revision ID: 987cf31d0a3b
Revises: 7171cd370743
Create Date: 2018-08-31 17:07:16.675885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987cf31d0a3b'
down_revision = '7171cd370743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=15), nullable=False),
    sa.Column('is_launched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'create_time')
    op.drop_table('wish')
    # ### end Alembic commands ###
